services:
  - type: web
    name: s-paysecure
    env: node
    region: singapore
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URL
        sync: false
